on:
  push:
    branches:
      - dev
      - main

jobs: 
  deploy-to-server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{github.repository}}:${{ github.sha }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop ${{github.repository}} || true
            docker rm ${{github.repository}} || true
            docker pull ${{github.repository}}:${{ github.sha }}
            docker run -d \
              --name ${{github.repository}} \
              -p 1112:1112 \
              ${{github.repository}}:${{ github.sha }}